# Generated by Django 6.1.1 on 2026-09-28 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Destination name, e.g. Paris.', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly name. Generated automatically from the name.', max_length=220, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('relaxation', 'Relaxation')], max_length=20)),
                ('climate', models.CharField(choices=[('tropical', 'Tropical'), ('dry', 'Dry'), ('temperate', 'Temperate'), ('continental', 'Continental'), ('polar', 'Polar')], max_length=20)),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('avg_daily_cost', models.DecimalField(decimal_places=2, help_text='Average daily cost per traveler.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country', 'category'], name='destination_country_c7c612_idx'), models.Index(fields=['climate'], name='destination_climate_5ffe0c_idx'), models.Index(fields=['avg_daily_cost'], name='destination_avg_dai_7024ce_idx'), models.Index(fields=['is_active'], name='destination_is_acti_09f11c_idx')],
            },
        ),
    ]
