# Generated by Django 6.1.1 on 2026-09-28 16:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Trip title.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Trip summary or notes.')),
                ('start_date', models.DateField(help_text='Trip start date.')),
                ('end_date', models.DateField(help_text='Trip end date.')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Total target budget.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_spent', models.DecimalField(decimal_places=2, default=0, help_text='Tracked actual expenditure.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Whether trip is publicly discoverable.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='shared_itineraries', through='itineraries.Collaboration', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(help_text='Target destination.', on_delete=django.db.models.deletion.PROTECT, related_name='itineraries', to='destinations.destination')),
                ('owner', models.ForeignKey(help_text='Owner/creator of the trip.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Itinerary',
                'verbose_name_plural': 'Itineraries',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(help_text='Day focus/title.', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notes for the day.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activities', models.ManyToManyField(blank=True, related_name='daily_plans', to='bookings.activity')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='itineraries.itinerary')),
            ],
            options={
                'verbose_name': 'Daily Plan',
                'verbose_name_plural': 'Daily Plans',
                'ordering': ['day_number'],
            },
        ),
        migrations.AddField(
            model_name='collaboration',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='itineraries.itinerary'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['owner', 'status'], name='itineraries_owner_i_768523_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['start_date', 'end_date'], name='itineraries_start_d_ad6b7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('itinerary', 'day_number')},
        ),
        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together={('itinerary', 'user')},
        ),
    ]
