# Generated by Django 6.1.1 on 2026-09-28 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Accommodation property name.', max_length=200)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('rental', 'Vacation Rental'), ('resort', 'Resort'), ('bnb', 'B&B')], help_text='Property type.', max_length=10)),
                ('description', models.TextField(help_text='Overview and amenities description.')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Nightly rate.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_guests', models.PositiveIntegerField(default=2, help_text='Maximum guest capacity.')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenities e.g. WiFi, Pool.')),
                ('address', models.CharField(help_text='Physical address.', max_length=300)),
                ('contact_email', models.EmailField(help_text='Contact email.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone.', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodations/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(help_text='Target destination.', on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Activity title.', max_length=200)),
                ('category', models.CharField(choices=[('tour', 'Tour'), ('attraction', 'Attraction'), ('dining', 'Dining'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('outdoor', 'Outdoor')], help_text='Activity category.', max_length=20)),
                ('description', models.TextField(help_text='Description of experience.')),
                ('duration_hours', models.DecimalField(decimal_places=1, help_text='Duration in hours.', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost per person.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, help_text='Prerequisites or clothing recommendations.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(help_text='Target destination.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(help_text='Date of booking.')),
                ('check_in', models.DateField(blank=True, help_text='Check-in date for accommodation.', null=True)),
                ('check_out', models.DateField(blank=True, help_text='Check-out date for accommodation.', null=True)),
                ('guests_count', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Total calculated booking price.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('confirmation_code', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.accommodation')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.activity')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
